server:
  port: 8081

spring:
  application:
    name: race-query-service
  mvc:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET,POST,PATCH,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
rabbitmq:
  exchange: race.exchange
  queue-created: race.created.queue
  queue-deleted: race.deleted.queue
  queue-updated: race.updated.queue
  routing-key-created: race.created
  routing-key-deleted: race.deleted
  routing-key-updated: race.updated
  queue-application-deleted: application.deleted.queue
  routing-key-application-deleted: application.deleted

logging:
  level:
    root: INFO
    com.trail.query: DEBUG

jwt:
  secret: 58cb2d122cb82a7fd1e3d03c1425fd2bf4a4c8679c5229b4621b01f80cde031ec36ffb4bc5e08bc33554e7d88eabbe0bd30c4d48